# Generated by Django 4.0.3 on 2023-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='in_statistics',
            field=models.BooleanField(blank=True, null=True, verbose_name='Учитывать в статистике'),
        ),
    ]
