# Generated by Django 4.0.3 on 2023-12-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0002_well_contractordrill_alter_well_in_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='сontractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='Field.contractordrill', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='well',
            name='T1_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание сопровождения до Т1'),
        ),
        migrations.AlterField(
            model_name='well',
            name='T3_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало сопровождения до Т3'),
        ),
    ]
