# Generated by Django 4.0.3 on 2023-12-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0003_well_сontractor_alter_well_t1_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='сontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='Field.contractordrill', verbose_name='Подрядчик'),
        ),
    ]
