# Generated by Django 4.0.3 on 2023-11-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticNNBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Статический замер ННБ',
                'verbose_name_plural': 'Статические замеры ННБ',
                'db_table': 'meas_static_NNB',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='ReportIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_dynamic_depth', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические глубина')),
                ('raw_dynamic_corner', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические угол')),
                ('raw_dynamic_depth_excel', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические глубина excel')),
                ('raw_dynamic_corner_excel', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические угол excel')),
                ('raw_dynamic_list_name', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические лист эксель')),
                ('nnb_static_depth', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ глубина')),
                ('nnb_static_corner', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ угол')),
                ('nnb_static_azimut', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ азимут')),
                ('nnb_static_list_name', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ лист эксель')),
                ('nnb_static_exclude_proj', models.BooleanField(default=False, verbose_name='Флаг на исключение проекции')),
                ('nnb_dynamic_depth', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ глубина')),
                ('nnb_dynamic_corner', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ угол')),
                ('nnb_dynamic_azimut', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ азимут')),
                ('nnb_dynamic_list_name', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ лист эксель')),
                ('igirgi_static_depth', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ глубина')),
                ('igirgi_static_corner', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ угол')),
                ('igirgi_static_azimut', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ азимут')),
                ('igirgi_list_name', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ лист эксель')),
                ('plan_depth', models.CharField(max_length=10, null=True, verbose_name='Плановая траектория глубина')),
                ('plan_corner', models.CharField(max_length=10, null=True, verbose_name='Плановая траектория угол')),
                ('plan_azimut', models.CharField(max_length=10, null=True, verbose_name='Плановая траектория азимут')),
                ('plan_list_name', models.CharField(max_length=10, null=True, verbose_name='Плановая траектория лист эксель')),
                ('nnb_dynamic_read', models.IntegerField(null=True, verbose_name='Считываем динамические данные  от ННБ с этой строки')),
                ('nnb_static_read', models.IntegerField(null=True, verbose_name='Считываем статические данные от ННБ с этой строки')),
                ('plan_str', models.IntegerField(null=True, verbose_name='Считываем данные плана с этой строки')),
                ('igirgi_str', models.IntegerField(null=True, verbose_name='Считываем данные статика ИГиРГИ с этой строки')),
                ('raw_str', models.IntegerField(null=True, verbose_name='Считываем сырые данные с этой строки')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Индекс для формы',
                'verbose_name_plural': 'Индексы для формы',
                'db_table': 'report_trajectory_index',
            },
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Сырой замер',
                'verbose_name_plural': 'Сырые замер',
                'db_table': 'meas_raw',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='ProjectionParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X (Запад/Восток)')),
                ('hor_x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X (Запад/Восток)')),
                ('hor_x_del', models.IntegerField(null=True, verbose_name='Шаг по X (Запад/Восток)')),
                ('hor_y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y (Юг/Север)')),
                ('hor_y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y (Юг/Север)')),
                ('hor_y_del', models.IntegerField(null=True, verbose_name='Шаг по Y (Юг/Север)')),
                ('ver_x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X (Вертикальная секция)')),
                ('ver_x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X (Вертикальная секция)')),
                ('ver_x_del', models.IntegerField(null=True, verbose_name='Шаг по X (Вертикальная секция)')),
                ('ver_y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y (Абсолютная отметка)')),
                ('ver_y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y (Абсолютная отметка)')),
                ('ver_y_del', models.IntegerField(null=True, verbose_name='Шаг по Y (Абсолютная отметка)')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_params', to='Field.wellbore', verbose_name='Параметры преокции')),
            ],
            options={
                'verbose_name': 'Параметры для построения проекции',
                'verbose_name_plural': 'Параметры для построения проекции',
                'db_table': 'report_proj_graph',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('plan_version', models.CharField(max_length=20, null=True, verbose_name='версия плана')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Замер плановой траектории',
                'verbose_name_plural': 'Замеры плановой траектории',
                'db_table': 'meas_plan',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='InterpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Замер интерполированной плановой траектории',
                'verbose_name_plural': 'Замеры интерполированной плановой траектории',
                'db_table': 'meas_intr_plan',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='IgirgiStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('comment', models.TextField(null=True, verbose_name='комментарий')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Статический замер ИГИРГИ',
                'verbose_name_plural': 'Статические замеры ИГИРГИ',
                'db_table': 'meas_static_igirgi',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='IgirgiDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Динамический замер ИГИРГИ',
                'verbose_name_plural': 'Динамические замеры ИГИРГИ',
                'db_table': 'meas_dynamic_igirgi',
                'ordering': ['depth'],
            },
        ),
        migrations.CreateModel(
            name='DynamicNNBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Динамический замер ННБ',
                'verbose_name_plural': 'Динамические замеры ННБ',
                'db_table': 'meas_dynamic_NNB',
                'ordering': ['depth'],
            },
        ),
    ]
