# Generated by Django 4.0.3 on 2023-12-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0003_well_сontractor_alter_well_t1_end_and_more'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionparam',
            name='wellbore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_params', to='Field.wellbore', verbose_name='Параметры проекции'),
        ),
        migrations.CreateModel(
            name='Graf6Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X')),
                ('x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X')),
                ('x_del', models.IntegerField(null=True, verbose_name='Шаг по X')),
                ('y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y')),
                ('y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y')),
                ('y_del', models.IntegerField(null=True, verbose_name='Шаг по Y')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore')),
            ],
            options={
                'db_table': 'report_graph6',
            },
        ),
        migrations.CreateModel(
            name='Graf5Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X')),
                ('x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X')),
                ('x_del', models.IntegerField(null=True, verbose_name='Шаг по X')),
                ('y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y')),
                ('y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y')),
                ('y_del', models.IntegerField(null=True, verbose_name='Шаг по Y')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore')),
            ],
            options={
                'db_table': 'report_graph5',
            },
        ),
        migrations.CreateModel(
            name='Graf4Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X')),
                ('x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X')),
                ('x_del', models.IntegerField(null=True, verbose_name='Шаг по X')),
                ('y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y')),
                ('y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y')),
                ('y_del', models.IntegerField(null=True, verbose_name='Шаг по Y')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore')),
            ],
            options={
                'db_table': 'report_graph4',
            },
        ),
        migrations.CreateModel(
            name='Graf3Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X')),
                ('x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X')),
                ('x_del', models.IntegerField(null=True, verbose_name='Шаг по X')),
                ('y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y')),
                ('y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y')),
                ('y_del', models.IntegerField(null=True, verbose_name='Шаг по Y')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore')),
            ],
            options={
                'db_table': 'report_graph3',
            },
        ),
        migrations.CreateModel(
            name='Graf2Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X')),
                ('x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X')),
                ('x_del', models.IntegerField(null=True, verbose_name='Шаг по X')),
                ('y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y')),
                ('y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y')),
                ('y_del', models.IntegerField(null=True, verbose_name='Шаг по Y')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore')),
            ],
            options={
                'db_table': 'report_graph2',
            },
        ),
        migrations.CreateModel(
            name='Graf1Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X')),
                ('x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X')),
                ('x_del', models.IntegerField(null=True, verbose_name='Шаг по X')),
                ('y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y')),
                ('y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y')),
                ('y_del', models.IntegerField(null=True, verbose_name='Шаг по Y')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore')),
            ],
            options={
                'db_table': 'report_graph1',
            },
        ),
    ]
