# Generated by Django 4.0.3 on 2023-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_projectionparam_wellbore_graf6param_graf5param_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graf1param',
            name='x_del',
            field=models.FloatField(null=True, verbose_name='Шаг по X'),
        ),
        migrations.AlterField(
            model_name='graf1param',
            name='x_max',
            field=models.FloatField(verbose_name='Максимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf1param',
            name='x_min',
            field=models.FloatField(verbose_name='Минимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf1param',
            name='y_del',
            field=models.FloatField(null=True, verbose_name='Шаг по Y'),
        ),
        migrations.AlterField(
            model_name='graf1param',
            name='y_max',
            field=models.FloatField(verbose_name='Максимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf1param',
            name='y_min',
            field=models.FloatField(verbose_name='Минимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='x_del',
            field=models.FloatField(null=True, verbose_name='Шаг по X'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='x_max',
            field=models.FloatField(verbose_name='Максимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='x_min',
            field=models.FloatField(verbose_name='Минимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='y_del',
            field=models.FloatField(null=True, verbose_name='Шаг по Y'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='y_max',
            field=models.FloatField(verbose_name='Максимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='y_min',
            field=models.FloatField(verbose_name='Минимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='x_del',
            field=models.FloatField(null=True, verbose_name='Шаг по X'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='x_max',
            field=models.FloatField(verbose_name='Максимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='x_min',
            field=models.FloatField(verbose_name='Минимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='y_del',
            field=models.FloatField(null=True, verbose_name='Шаг по Y'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='y_max',
            field=models.FloatField(verbose_name='Максимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='y_min',
            field=models.FloatField(verbose_name='Минимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='x_del',
            field=models.FloatField(null=True, verbose_name='Шаг по X'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='x_max',
            field=models.FloatField(verbose_name='Максимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='x_min',
            field=models.FloatField(verbose_name='Минимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='y_del',
            field=models.FloatField(null=True, verbose_name='Шаг по Y'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='y_max',
            field=models.FloatField(verbose_name='Максимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='y_min',
            field=models.FloatField(verbose_name='Минимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='x_del',
            field=models.FloatField(null=True, verbose_name='Шаг по X'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='x_max',
            field=models.FloatField(verbose_name='Максимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='x_min',
            field=models.FloatField(verbose_name='Минимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='y_del',
            field=models.FloatField(null=True, verbose_name='Шаг по Y'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='y_max',
            field=models.FloatField(verbose_name='Максимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='y_min',
            field=models.FloatField(verbose_name='Минимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='x_del',
            field=models.FloatField(null=True, verbose_name='Шаг по X'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='x_max',
            field=models.FloatField(verbose_name='Максимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='x_min',
            field=models.FloatField(verbose_name='Минимальное значение по X'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='y_del',
            field=models.FloatField(null=True, verbose_name='Шаг по Y'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='y_max',
            field=models.FloatField(verbose_name='Максимальное значение по Y'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='y_min',
            field=models.FloatField(verbose_name='Минимальное значение по Y'),
        ),
    ]
