# Generated by Django 4.0.3 on 2023-12-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0004_alter_well_сontractor'),
        ('report', '0004_alter_graf1param_wellbore_alter_graf2param_wellbore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graf1param',
            name='wellbore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore'),
        ),
        migrations.AlterField(
            model_name='graf2param',
            name='wellbore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore'),
        ),
        migrations.AlterField(
            model_name='graf3param',
            name='wellbore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore'),
        ),
        migrations.AlterField(
            model_name='graf4param',
            name='wellbore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore'),
        ),
        migrations.AlterField(
            model_name='graf5param',
            name='wellbore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore'),
        ),
        migrations.AlterField(
            model_name='graf6param',
            name='wellbore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.wellbore'),
        ),
    ]
