# Generated by Django 4.0.3 on 2023-11-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_title', models.CharField(max_length=100, unique=True, verbose_name='Название телесистемы')),
                ('CX', models.CharField(max_length=50, verbose_name='GX')),
                ('CY', models.CharField(max_length=50, verbose_name='GY')),
                ('CZ', models.CharField(max_length=50, verbose_name='GZ')),
                ('BX', models.CharField(max_length=50, verbose_name='BX')),
                ('BY', models.CharField(max_length=50, verbose_name='BY')),
                ('BZ', models.CharField(max_length=50, verbose_name='BZ')),
            ],
            options={
                'verbose_name': 'Телесистема',
                'verbose_name_plural': 'Телесистемы',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.TextField(max_length=200, verbose_name='Глубина')),
                ('CX', models.TextField(max_length=200, verbose_name='GX')),
                ('CY', models.TextField(max_length=200, verbose_name='GY')),
                ('CZ', models.TextField(max_length=200, verbose_name='GZ')),
                ('BX', models.TextField(max_length=200, verbose_name='BX')),
                ('BY', models.TextField(max_length=200, verbose_name='BY')),
                ('BZ', models.TextField(max_length=200, verbose_name='BZ')),
            ],
            options={
                'verbose_name': 'Лист заголовков',
                'verbose_name_plural': 'Листы заголовков',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(max_length=10, verbose_name='Глубина')),
                ('CX', models.FloatField(max_length=10, null=True, verbose_name='GX')),
                ('CY', models.FloatField(max_length=10, null=True, verbose_name='GY')),
                ('CZ', models.FloatField(max_length=10, null=True, verbose_name='GZ')),
                ('BX', models.FloatField(max_length=10, null=True, verbose_name='BX')),
                ('BY', models.FloatField(max_length=10, null=True, verbose_name='BY')),
                ('BZ', models.FloatField(max_length=10, null=True, verbose_name='BZ')),
                ('Btotal_corr', models.FloatField(null=True, verbose_name='Btotal_corr')),
                ('DIP_corr', models.FloatField(null=True, verbose_name='DIP_corr')),
                ('in_statistics', models.BooleanField(null=True, verbose_name='Учитывать в статистике')),
                ('comment', models.TextField(blank='True', default='', null=True, verbose_name='Комментарий')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='AxesFileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GX', models.CharField(max_length=4, verbose_name='GX')),
                ('GY', models.CharField(max_length=4, verbose_name='GY')),
                ('GZ', models.CharField(max_length=4, verbose_name='GZ')),
                ('BX', models.CharField(max_length=4, verbose_name='BX')),
                ('BY', models.CharField(max_length=4, verbose_name='BY')),
                ('BZ', models.CharField(max_length=4, verbose_name='BZ')),
                ('units', models.CharField(max_length=4, verbose_name='Строка единиц измерения')),
                ('string_index', models.CharField(max_length=4, verbose_name='Импорт со строки')),
                ('depth', models.CharField(max_length=4, verbose_name='Глубина')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.device')),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Индесы телесистемы',
                'verbose_name_plural': 'Индесы телесистемы',
            },
        ),
    ]
