# Generated by Django 4.0.3 on 2023-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_author_alter_post_text_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(max_length=63),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
